export const BIKE_LIST_REQUEST = 'BIKE_LIST_REQUEST';
export const BIKE_LIST_SUCCESS = 'BIKE_LIST_SUCCESS';
export const BIKE_LIST_FAIL = 'BIKE_LIST_FAIL';

export const BIKE_REQUEST = 'BIKE_REQUEST';
export const BIKE_SUCCESS = 'BIKE_SUCCESS';
export const BIKE_FAIL = 'BIKE_FAIL';

export const BIKE_DELETE_REQUEST = 'BIKE_DELETE_REQUEST';
export const BIKE_DELETE_SUCCESS = 'BIKE_DELETE_SUCCESS';
export const BIKE_DELETE_FAIL = 'BIKE_DELETE_FAIL';

export const BIKE_CREATE_REQUEST = 'BIKE_CREATE_REQUEST';
export const BIKE_CREATE_SUCCESS = 'BIKE_CREATE_SUCCESS';
export const BIKE_CREATE_FAIL = 'BIKE_CREATE_FAIL';
export const BIKE_CREATE_RESET = 'BIKE_CREATE_RESET';

export const BIKE_UPDATE_REQUEST = 'BIKE_UPDATE_REQUEST';
export const BIKE_UPDATE_SUCCESS = 'BIKE_UPDATE_SUCCESS';
export const BIKE_UPDATE_FAIL = 'BIKE_UPDATE_FAIL';
export const BIKE_UPDATE_RESET = 'BIKE_UPDATE_RESET';

export const BIKE_CREATE_REVIEW_REQUEST = 'BIKE_CREATE_REVIEW_REQUEST';
export const BIKE_CREATE_REVIEW_SUCCESS = 'BIKE_CREATE_REVIEW_SUCCESS';
export const BIKE_CREATE_REVIEW_FAIL = 'BIKE_CREATE_REVIEW_FAIL';
export const BIKE_CREATE_REVIEW_RESET = 'BIKE_CREATE_REVIEW_RESET';

export const TOP_BIKE_REQUEST = 'TOP_BIKE_REQUEST';
export const TOP_BIKE_SUCCESS = 'TOP_BIKE_SUCCESS';
export const TOP_BIKE_FAIL = 'TOP_BIKE_FAIL';

