export const DASHBOARD_USERSDATA_REQUEST = 'DASHBOARD_USERSDATA_REQUEST';
export const DASHBOARD_USERSDATA_SUCCESS = 'DASHBOARD_USERSDATA_SUCCESS';
export const DASHBOARD_USERSDATA_FAIL = 'DASHBOARD_USERSDATA_FAIL';

export const DASHBOARD_ORDERDATA_REQUEST = 'DASHBOARD_ORDERDATA_REQUEST';
export const DASHBOARD_ORDERDATA_SUCCESS = 'DASHBOARD_ORDERDATA_SUCCESS';
export const DASHBOARD_ORDERDATA_FAIL = 'DASHBOARD_ORDERDATA_FAIL';

export const DASHBOARD_UNDELIVERED_REQUEST = 'DASHBOARD_UNDELIVERED_REQUEST';
export const DASHBOARD_UNDELIVERED_SUCCESS = 'DASHBOARD_UNDELIVERED_SUCCESS';
export const DASHBOARD_UNDELIVERED_FAIL = 'DASHBOARD_UNDELIVERED_FAIL';