export const SETTING_ITEMSPP_REQUEST = 'SETTING_ITEMSPP_REQUEST';
export const SETTING_ITEMSPP_SUCCESS = 'SETTING_ITEMSPP_SUCCESS';
export const SETTING_ITEMSPP_FAIL = 'SETTING_ITEMSPP_FAIL';

export const SETTING_ITEMSPP_UPDATE_REQUEST = 'SETTING_ITEMSPP_UPDATE_REQUEST';
export const SETTING_ITEMSPP_UPDATE_SUCCESS = 'SETTING_ITEMSPP_UPDATE_SUCCESS';
export const SETTING_ITEMSPP_UPDATE_FAIL = 'SETTING_ITEMSPP_UPDATE_FAIL';
export const SETTING_ITEMSPP_UPDATE_RESET = 'SETTING_ITEMSPP_UPDATE_RESET';